services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    restart: no
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD: user1pass
    volumes:
      - ./mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
